version: '3.8'

services:
  # Database: MongoDB (Dùng cho Mongoose)
  mongodb:
    image: mongo:7.0
    container_name: baucua-db-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-adminpass}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  # Backend App
  backend:
    build: ./backend
    container_name: baucua-backend
    restart: always
    environment:
      PORT: 5000
      DATABASE_URL: ${DATABASE_URL}
      MONGODB_URI: "mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-adminpass}@mongodb:27017/baucua?authSource=admin"
      JWT_SECRET: ${JWT_SECRET:-secret_key_change_me}
      NODE_ENV: production
    depends_on:
      - mongodb
    ports:
      - "5000:5000"

  # Frontend App (Nginx phục vụ file tĩnh và Proxy)
  frontend:
    build: ./frontend
    container_name: baucua-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongo_data:
